version: '3'
services:
  app:
    container_name: indigitest-api-server
    restart: always
    build: .
    links: 
      - postgres
    ports:
      - "9090:9090"
  postgres:
    container_name: postgres
    restart: always
    build: ./scripts
    volumes: 
      - ./dockerdata/db:/var/lib/postgresql/data
    
