const faker = require('faker')
const Id = require('../../src/Id')
const { languages } = require('../../src/constants.json')

//second parameter hemisphere: 
//    North by default, 
//    any other value will imply South.

function makeFakeUser (
  overrides, 
  options = { 
    hemisphere : 'North', 
    flatten: false
  }
) {
 const user = options.flatten ? {
   id: Id.makeId(),
   username: limitStringLength(faker.internet.userName, 30),
   email: limitStringLength(faker.internet.email, 30),
   password: faker.internet.password(),
   longitude: faker.address.longitude(),
   latitude: options.hemisphere === 'North' 
        ? Math.abs(faker.address.latitude()) 
        : Math.abs(faker.address.latitude())*(-1),
   browserlang: languages[Math.floor(Math.random()*languages.length)]
 } : {
   id: Id.makeId(),
   username: limitStringLength(faker.internet.userName, 30),
   email: limitStringLength(faker.internet.email, 30),
   password: faker.internet.password(),
   source: {
     longitude: faker.address.longitude(),
     latitude: options.hemisphere === 'North' 
        ? Math.abs(faker.address.latitude()) 
        : Math.abs(faker.address.latitude())*(-1),
     browserlang: languages[Math.floor(Math.random()*languages.length)]
   }
 }

  return {
    ...user,
    ...overrides
  }
}

//temporarily limited the length of autogenerated username and password to 30 characters
function limitStringLength( generator, maxLength ) {
  let str = generator()
  if (str.length > maxLength) {
    str = limitStringLength( generator, maxLength)
  }
  return str
}

module.exports = makeFakeUser
